################
#shiny app to simulate changes in n, cov(x,e)
#dc - 2.4.24
################
library(shiny)
library(tidyverse)
library(ggplot2)
library(faux)
library(patchwork)

# Define UI for application that plots b, se
ui <- fluidPage(

    # Application title
    titlePanel("Simulating the OLS regression"),

    # Sidebar with a slider input for mean, sd 
    sidebarLayout(
        sidebarPanel(
            sliderInput("N",
                        "Sample size, N:",
                        min = 0,
                        max = 1500,
                        value = 500, step=100),
            
            br(),
            
            sliderInput("rhox1e",
                        label = HTML("&rho; (Cov(x1,&epsilon;)):"),
                        min = -1,
                        max = 1 ,
                        value = 0, step=.1),
            
            br(),
            
            sliderInput("rhox1x2",
                        label = "Cov(x1,x2)):",
                        min = -1,
                        max = 1,
                        value = 0, step=.1 )
        ),

       
        
        mainPanel(
          "OLS linear regression, data generated by",
          code("y = .5 + x1 + 2*x2 + e."),  
          "Simulation varies sample size, correlation of x1 and the error, and correlation
          or x1 and x2. Plots examine recovery of coefficients and standard errors.",
           plotOutput("distPlot1")
    ))
)


# Define server logic required to draw distributions
server <- function(input, output) {
    output$distPlot1 <- renderPlot({
        # generate parameters based on input$  from ui.R
      results <- data.frame ( var = character (0), coef = numeric(0), se = numeric (0), n = numeric (0))
      
      for(i in seq(10,input$N,10)) { 
        set.seed(12345)
        data <- tibble(
          X <- rnorm_multi(i, 3, 
                           mu=c(0, 0, 0), 
                           sd=1,
                           r = c(input$rhox1x2, input$rhox1e, 0.0),
                           varnames=c("x1", "x2", "e"))
        ) %>%
          mutate(y = .5 + 1*x1 + 2*x2 + e)
        
        mod <- (lm(y ~ x1 + x2, data=data))
        
        results[((i-9)*3-2):((i-9)*3),1:4] <- data.frame ( var = c("x0","x1","x2"), coef(summary(mod))[,1:2], i)
        
      }
      
      results <-data.frame(results, t=results$coef/results$se)
      
      
      p1 <- ggplot(data=results%>%filter(!is.na(n)), aes(x=n, y=coef, color=var)) +
        geom_line() +
        labs ( colour = NULL, x = "Sample Size", y =  "Estimated Coefficient" ) +
        theme ( legend.position = "bottom",
                legend.key = element_blank() ) 
        
       
      
      p2 <- ggplot(data=results%>%filter(!is.na(n)), aes(x=n, y=se, color=var)) +
        geom_line() +
        labs ( colour = NULL, x = "Sample Size", y =  "Estimated Standard Error" ) +
        theme ( legend.position = "bottom",
                legend.key = element_blank() )
      
      
      p1 | p2
    })
    
    # output$distPlot2 <- renderPlot({
    #   # generate parameters based on input$  from ui.R
    #   x    <- runif(1000, min = -4, max = 4)
    #   mean <-  input$mean
    #   sd <- input$sd
    #   npdf <- dnorm(x, mean = mean, sd = sd)
    #   lpdf <- dlogis(x, location=mean, scale=sd)
    #   plotdata2 <- data.frame(x, npdf, lpdf)
    #   # draw the pdf with the specified mean/sd
    #   ggplot()+ geom_line(data = plotdata2, aes(x=x, y=lpdf, lty=1), color="gray20", lty=1)+
    #     geom_line(data = plotdata2, aes(x=x, y=npdf), color="gray20", lty=2)+
    #     labs(x="z", y="Probability(z)") 
    # 
    #   
    # })
}


# Run the application 
shinyApp(ui = ui, server = server)
