################
#shiny app to simulate changes cov(x,e), cov(x1,x2)
#dc - spring 2024
#to run from rstudio, shiny::runGitHub('ML22', 'clavedark', subdir = "docs/simulation")
################
library(shiny)
library(ggplot2)
library(mvtnorm)
library(patchwork)
library(faux)

# Define UI for application that plots b, se
ui <- fluidPage(
  
  # Application title
  titlePanel("Simulating the OLS regression"),
  
  # Sidebar with a slider input for mean, sd 
  sidebarLayout(
    sidebarPanel(
      radioButtons("rho", "Correlation:",
                   c("x1, x2" = "xx",
                     "x1, e" = "xe")),
      sliderInput("rho",
                  label = HTML("&rho; (Cov(x1,&epsilon;)):"),
                  min = -1,
                  max = 1 ,
                  value = 0, step=.1),
      br()

    ),
    
    
    
    mainPanel(
      "OLS linear regression, data generated by",
      code("y = .5 + x1 + 2*x2 + e."),  
      "Simulation varies correlation of x1 and the error, and correlation
          of x1 and x2. Plots examine recovery of coefficients and standard errors.",
      
    ))
)


# Define server logic required to draw distributions
server <- function(input, output) {
  
  # Reactive expression to generate the requested distribution ----
  # This is called whenever the inputs change. The output functions
  # defined below then use the value computed from this expression
  d <- reactive({
    rho <- switch(input$rho,
                   xx = rnorm,
                   xe = )
    
    dist(input$n)
  })
  
  
  
  output$distPlot2 <- renderPlot({
    # generate parameters based on input$  from ui.R
    resultsR <- data.frame ( var = character (0), coef = numeric(0), se = numeric (0), rho = numeric (0))
    
    j=1
    for(r in seq(-.95,.95,.1)) { 
      set.seed(12345)
      datar <- tibble(
        Xr <- rnorm_multi(1500, 3, 
                         mu=c(0, 0, 0), 
                         sd=1,
                         r = c(input$rhox1x2, r, 0.0),
                         varnames=c("x1", "x2", "e"))
      ) %>%
        mutate(yr = .5 + 1*x1 + 2*x2 + e)
      
      modr <- (lm(yr ~ x1 + x2, data=datar))
      
      resultsR[((j)*3-2):((j)*3),1:4] <- data.frame ( var = c("x0","x1","x2"), coef(summary(modr))[,1:2], rho=r)
      
      j=j+1
    }
    
    resultsR <-data.frame(resultsR, t=resultsR$coef/resultsR$se)
    
    
    r1 <- ggplot(data=resultsR%>%filter(!is.na(rho)), aes(x=rho, y=coef, color=var)) +
      geom_line() +
      labs ( colour = NULL, x = "Correlation x1, e", y =  "Estimated Coefficient" ) +
      theme ( legend.position = "bottom",
              legend.key = element_blank() ) 
    
    
    
    r2 <- ggplot(data=resultsR%>%filter(!is.na(rho)), aes(x=rho, y=se, color=var)) +
      geom_line() +
      labs ( colour = NULL, x = "Correlation x1, e", y =  "Estimated Standard Error" ) +
      theme ( legend.position = "bottom",
              legend.key = element_blank() )
    
    
    r1 | r2
  })  

  
}


# Run the application 
shinyApp(ui = ui, server = server)
